# Generated by Django 2.1.1 on 2018-09-20 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Major',
            fields=[
                ('major_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stu_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('classroom', models.CharField(max_length=100)),
                ('major_id', models.ManyToManyField(to='app1.Major')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('card_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='major',
            name='t_id',
            field=models.ManyToManyField(to='app1.Teacher'),
        ),
    ]
