"""empty message

Revision ID: 2c7acf5eb4af
Revises: 3678c6e6df3a
Create Date: 2018-10-18 11:53:26.902214

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2c7acf5eb4af'
down_revision = '3678c6e6df3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grade',
    sa.Column('g_id', sa.Integer(), nullable=False),
    sa.Column('g_name', sa.Text(), nullable=False),
    sa.Column('g_num', sa.Integer(), nullable=True),
    sa.Column('g_time', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('g_id')
    )
    op.create_table('t_g',
    sa.Column('t_id', sa.String(length=100), nullable=True),
    sa.Column('g_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['g_id'], ['grade.g_id'], ),
    sa.ForeignKeyConstraint(['t_id'], ['teacher.t_id'], )
    )
    op.add_column('student', sa.Column('s_gid', sa.Integer(), nullable=True))
    op.drop_constraint('student_ibfk_1', 'student', type_='foreignkey')
    op.create_foreign_key(None, 'student', 'grade', ['s_gid'], ['g_id'])
    op.drop_column('student', 's_tid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('s_tid', mysql.VARCHAR(length=100), nullable=True))
    op.drop_constraint(None, 'student', type_='foreignkey')
    op.create_foreign_key('student_ibfk_1', 'student', 'teacher', ['s_tid'], ['t_id'])
    op.drop_column('student', 's_gid')
    op.drop_table('t_g')
    op.drop_table('grade')
    # ### end Alembic commands ###
