"""empty message

Revision ID: 3678c6e6df3a
Revises: 
Create Date: 2018-10-17 10:43:39.048340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3678c6e6df3a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher',
    sa.Column('t_id', sa.String(length=100), nullable=False),
    sa.Column('t_name', sa.String(length=20), nullable=False),
    sa.Column('t_pass', sa.String(length=50), nullable=False),
    sa.Column('t_tel', sa.String(length=11), nullable=False),
    sa.Column('t_photo', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('t_id')
    )
    op.create_table('student',
    sa.Column('s_id', sa.String(length=100), nullable=False),
    sa.Column('s_name', sa.String(length=20), nullable=False),
    sa.Column('s_pass', sa.String(length=50), nullable=False),
    sa.Column('s_tel', sa.String(length=11), nullable=False),
    sa.Column('s_photo', sa.String(length=100), nullable=True),
    sa.Column('s_sex', sa.String(length=10), nullable=False),
    sa.Column('s_tid', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['s_tid'], ['teacher.t_id'], ),
    sa.PrimaryKeyConstraint('s_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student')
    op.drop_table('teacher')
    # ### end Alembic commands ###
