"""empty message

Revision ID: 8d5fbddcb161
Revises: 2c7acf5eb4af
Create Date: 2018-10-18 14:39:39.054511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d5fbddcb161'
down_revision = '2c7acf5eb4af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher', sa.Column('t_pos', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teacher', 't_pos')
    # ### end Alembic commands ###
