# Generated by Django 2.1.1 on 2018-09-19 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stu_msg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('age', models.IntegerField(max_length=3)),
                ('sex', models.CharField(max_length=5)),
                ('username', models.ForeignKey(on_delete=True, to='app1.Accounts')),
            ],
        ),
    ]
